name: Build and Publish

on:
  workflow_dispatch:
    branches: [main]
    inputs:
      version:
        description: 'Version to bump `package.json` to'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Version bump
      run: npm version ${{ github.event.inputs.version }}

    - name: Install dependencies
      run: npm install

    - name: Compile and Package
      run: npm run package
      env:
        CI: true

    - name: Publish
      run: npm run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: "timheuer-containerize"
        path: "**/*.vsix"

    - name: Tag and Release
      id: tag_release
      uses: softprops/action-gh-release@v1
      with:
        body: Release ${{ github.event.inputs.version }}
        tag_name: ${{ github.event.inputs.version }}
        generate_release_notes: true
        files: |
          **/*.vsix